
name : Hello World Test

on :
  push :
    branches : [ "master", "develop" ]

jobs :
  hello_world_job :
    runs-on : ubuntu-latest
    name : A job to say hello

    strategy :
      fail-fast : false

      matrix :
        who-args : [ 'Mona the Octocat', 'Second' ]

    steps :
      - uses : actions/checkout@v4

      - id : foo
        uses : takahiro-itou/hello-world-composite-action@develop
        with :
          who-to-greet : ${{ matrix.who-args }}

      - run   : echo random-number "$RANDOM_NUMBER"
        shell : bash
        env   :
          RANDOM_NUMBER : ${{ steps.foo.outputs.random-number }}

      - run   : |
          echo common-value "${COMMON_VALUE}"
          echo cached-date  "${CACHED_DATE}"
        shell : bash
        env   :
          COMMON_VALUE : ${{ steps.foo.outputs.common-value }}
          CACHED_DATE  : ${{ steps.foo.outputs.cached-date }}

      - run : |
          pwd
          ls -alR
          md5sum -b ./init/*.txt
        shell : bash
