
name : Hello World Test

on :
  push :
    branches : [ "master", "develop" ]

jobs :
  hello_world_job :
    runs-on : ubuntu-latest
    name : A job to say hello
    steps :
      - uses : actions/checkout@v4
      - id : foo
        uses : takahiro-itou/hello-world-composite-action@v1
        with :
          who-to-greet : 'Mona the Octocat'
